Small fix
yzslab/php-libvirt-client pull request #8
Opened 2021-03-30 13:11 UTC by inode64

New words in dictionary and fix typo in readme.md

2021-03-30 13:48 UTC, yzslab requested changes

2021-03-30 14:33 UTC, inode64 commented
I'm sorry, fixed

2021-03-30 14:58 UTC, yzslab requested changes

2021-03-31 22:23 UTC, merged

2021-03-31 22:24 UTC, yzslab commented
> I don't know what I was thinking. :-)

Haha, sometimes I do the similiar thing too.
Thanks, merged.