add backingstore()
yzslab/php-libvirt-client pull request #9
Opened 2021-03-31 23:00 UTC by inode64

Am I on the right track?

2021-03-31 23:36 UTC, yzslab commented
Hi, it is good.
BackingStore can be nested used, like: 
```
  <disk type='file' device='disk'>
    <driver name='qemu' type='qcow2' queues='4'/>
    <source file='/var/lib/libvirt/images/domain.qcow'/>
    <backingStore type='file'>
      <format type='qcow2'/>
      <source file='/var/lib/libvirt/images/snapshot.qcow'/>
      <backingStore type='block'>
        <format type='raw'/>
        <source dev='/dev/mapper/base'/>
        <backingStore/>
      </backingStore>
    </backingStore>
    <target dev='vdd' bus='virtio'/>
  </disk>
```
My recommendation is implementing it too, just need a $singletonChildWrappers.

2021-03-31 23:41 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk.php
> + * @method BackingStore BackingStore()
Hi, this method, please rename to backingStore(), thanks.

2021-03-31 23:44 UTC, yzslab requested changes

2021-03-31 23:44 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk.php
> + * @method BackingStore BackingStore()
Hi, this method, please rename to backingStore(), thanks.

2021-03-31 23:56 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk/BackingStore.php
> +    public function active()
Hi, this method, I think naming as isActive will be better.

2021-03-31 23:57 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk/BackingStore.php
> +    public function active()
Just like this function: https://libvirt.org/php/api-reference.html#libvirt_domain_is_active

2021-04-01 05:51 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk.php
> +use YunInternet\Libvirt\Configuration\Domain\Device\Disk\backingStore;
Hi, the name of this class should still be "BackingStore". Only the method name should be "backingStore". As you can see, the method name of address is "address", but its class name is "Address".

Example: 
```
...
use YunInternet\Libvirt\Configuration\Domain\Device\Disk\BackingStore;
...
 * @method BackingStore backingStore()
...
class Disk ... {
    ...
    protected $singletonChildWrappers = [
        ...
        "backingStore" => BackingStore::class,
    ];
    ...
}
```
Then you can get your BackingStore instance by invoking $disk->backingStore().

2021-04-01 06:19 UTC, inode64 commented
I have prepared the support for nested classes
So prepare the structure

$disk->source()->fileSource(); ---> actual disk->fileSource();
$disk->backingStore()->source()->fileSource();


It would be no improvement to rename the case fileSource to GetFile when used with disk()->source()->GetFile();

2021-04-01 06:24 UTC, yzslab commented on src/YunInternet/Libvirt/Configuration/Domain/Device/Disk/backingStore.php
> +            $num = $this->backingStore()->Nested($num);
You should use $num += $this->backingStore()..., rather than require a parameter.

2021-04-01 06:55 UTC, inode64 commented
Am I missing something to correct?
Thanks

2021-04-01 12:03 UTC, yzslab commented
> Am I missing something to correct?
> Thanks

https://github.com/yzslab/php-libvirt-client/pull/10

2021-04-02 00:36 UTC, closed without merging